### ISSUE TITLE
Was this ever created with offline routing in mind?

### ISSUE THREAD

**Issue by geertbrit** [opentripplanner/OpenTripPlanner-iOS#6]
Or is a connection to some remote backend still needed to perform the actual calculations?

**Comment by abyrd** [comment]
Hi - the OpenTripPlanner-iOS depends on a connection to an OTP server, so it's not suitable for offline routing. Some OTP contributors may be working on products capable of offline routing in 2013, and any news on that front should be posted to the mailing list.

This system is used for tracking bugs -- please direct any further questions to our google group: opentripplanner-users

Thanks!
