### ISSUE TITLE
Documentation Available?

### ISSUE THREAD

**Issue by khare-ashwini** [opentripplanner/OpenTripPlanner-iOS#9]
Is there any sort of documentation available to work with this code base? I am working on a project which uses opentripplanner and any references for the iOS App would be immensely helpful.

Thanks!

**Comment by abyrd** [comment]
Hello, this project started as an effort to bring public transit trip planning to iOS when Google left. It basically functions but was never 100% completed; the project wrapped up when a bunch of good apps (some of them also based on OpenTripPlanner) filled the void. So it is not being maintained and I don't think there's any documentation beyond whatever you find in the repo. But feel free to make use of what you find here! 

This issue system is intended for bug tracking, so if you have any further questions or would like to ask around for information, you can use the opentripplanner-developers mailing list.
